server:
  service:
    type: LoadBalancer
  extraInitContainers:
    - name: prometheus-data-permission-fix
      image: busybox:1.28
      command: ['/bin/chmod', '-R', '777', '/data']
      securityContext:
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      volumeMounts:
        - name: storage-volume
          mountPath: /data

extraScrapeConfigs: |
  - job_name: api-metrics
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['host.minikube.internal:8004']

prometheus-node-exporter:
  enabled: true
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: nodename
