apiVersion: v1
kind: Pod
metadata:
  name: dp-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: '/usr/share/nginx/html'
          name: storage
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 500Mi
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: dp-pvc
