apiVersion: v1
kind: Pod
metadata:
  name: hostpath-test
spec:
  containers:
    - name: test-container
      image: busybox
      command: ['sh', '-c', 'tail -f /dev/null']
      volumeMounts:
        - name: test-volume
          mountPath: /mnt/test
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 500Mi
  volumes:
    - name: test-volume
      hostPath:
        path: /home/docker/test
        type: Directory
